stages:
    - build
    - test
    - review
    - stage
    - production
variables:
    DATABASE_URL: 'mongodb://mongo/user_posts'
    DOCKER_TLS_CERTDIR: ""

build_job:
  stage: build
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker images ls
  script:
    - echo 'Building'
    - docker build -t ${DOCKERHUB_USER}otus-reddit:${CI_COMMIT_TAG:-1.0.0}.${CI_COMMIT_SHORT_SHA:-0} ./docker-monolith
    - docker push ${DOCKERHUB_USER}/otus-reddit:${CI_COMMIT_TAG:-1.0.0}.${CI_COMMIT_SHORT_SHA:-0}
  after_script:
    - docker images ls

test_unit_job:
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  before_script:
    - cd reddit
    - bundle install
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
