global:
    slack_api_url: 'https://hooks.slack.com/services/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'

route:
    receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: 'sofya_tsiguro'
