version: '3.3'
services:
  db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    #build: ./ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${DOCKERHOST_PORT}:${REDDIT_PORT}/tcp
    networks:
        front_net:
          aliases:
            - ui
  post:
    #build: ./post-py
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
        back_net:
        front_net:
          aliases:
            - post
  comment:
    #build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
        back_net:
        front_net:
          aliases:
            - comment

volumes:
  post_db:

networks:
  front_net:
  back_net:
